#!/bin/bash

set -euo pipefail

usage() {
    cat <<eof >&2
usage: $0 <subject number> <block number>

    description
        run the task from a single entry point
eof
    exit 1
}

if [[ $# -eq 0 ]]; then
    usage
fi

SUBJ_NUM="$1"
BLOCK="$2"

matlab -nodisplay -r "addpath('functions'); run('$SUBJ_NUM', '$BLOCK')"
