#!/bin/bash

set -euo pipefail

for file in */*.wav
do
    newname=$(echo "$file" | sed 's/_.//g')
    rank=$(echo "$file" | sed 's/_.//')
    echo "Renaming $file to $newname"
    echo "$rank"
    #mv "$file" "$newname"
done
